version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"

  - package-ecosystem: pip
    directory: /doc
    schedule:
      interval: "weekly"

  - package-ecosystem: docker
    directory: /tests
    schedule:
      interval: "weekly"
