site_name: Heat
site_url: https://heat.readthedocs.io

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings
  - git-revision-date-localized
  - macros
  - mkdocs-jupyter:
      execute: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - toc

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - styles/extra.css

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Getting started: getting_started.md
  - Heat Tutorials:
        Overview: tutorials/tutorial.md
        30 minutes Welcome: tutorials/tutorial_30_minutes.md
        Parallel Computation: tutorials/tutorial_parallel_computation.md
        Cluster Analysis: tutorials/tutorial_clustering.md
        Notebook Gallery: tutorials/tutorial_notebook_gallery.md
        Setup:
          Local setup: tutorials/notebooks/0_setup/0_setup_local.ipynb
          JSC setup: tutorials/notebooks/0_setup/0_setup_jsc.ipynb
          HAICORE setup: tutorials/notebooks/0_setup/0_setup_haicore.ipynb
        Examples:
          Heat Basics: tutorials/notebooks/1_basics.ipynb
          Internals: tutorials/notebooks/2_internals.ipynb
          Loading and Preprocessing: tutorials/notebooks/3_loading_preprocessing.ipynb
          Matrix factorizations: tutorials/notebooks/4_matrix_factorizations.ipynb
          Clustering: tutorials/notebooks/5_clustering.ipynb
          Profiling: tutorials/notebooks/6_profiling.ipynb

  # - Documentation guide: documentation_howto.md
  - Case studies: case_studies.md
  - API Reference: api/index.md
