name: benchmarking-test

on:
  push:
    branches: [ bencharking-with-pytest-for-genkgo ]


jobs:
  run-benchmarks:
    name: benchmark automation
    runs-on: self-hosted
    steps:
      - uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            ml load GCC ParaStationMPI HDF5 netCDF Python
            source heat-venv/bin/activate
            jutil env activate -p haf
            cd fork/heat/benchmarks/pytest-benchmarks/
            ./run_benchmarks.sh
          host: ${{ secrets.HDFML_HOST }}
          username: ${{ secrets.HDFML_USER_NAME }}
          privateKey: ${{ secrets.HDFML_KEY}}
          passphrase: ${{ secrets.HDFML_PASSPHRASE }}
