name: Unit Tests Workflow

on:
  push:
    branches:
      - features/424-github-actions

jobs:
  run-unittests:
    name: ${{ matrix.image }} - ${{ matrix.processes }} processes unittests
    runs-on: ubuntu-latest
    container: docker://$simonsdockerid/heat_{{ matrix.image }}
    strategy:
      matrix:
        image: [ubuntu, fedora]
        processes: [1, 2, 3, 4, 7]
    steps:
      - uses: actions/checkout@v1
      - name: Run Pre-Commit
        shell: bash
        run: pre-commit run --all-files
      - name: Install Python Dependencies
        shell: bash
        run: |
          pip install -q -e .[hdf5,netcdf]
          pip list
      - name: Run Python Tests with ${{matrix.processes}} Processes
        shell: bash
        run: mpirun --oversubscribe --mca btl_vader_single_copy_mechanism none --mca btl ^openib --allow-run-as-root -np ${{ matrix.processes }} coverage run --source=heat --parallel-mode -m pytest heat/
      - name: Create Coverage Report
        shell: bash
        run: |
          coverage combine
          coverage report
          coverage xml
      - name: Upload Codevoc
        uses: actions/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
